<?php if ($this->pageCount) : ?>
  <div>
    <ul class="pagination">
      <!-- Link para a página anterior -->
      <?php if (isset($this->previous)) : ?>
        <li>
          <a href="<?= $this->url($this->route, [],
            ['query' => ['page' => $this->first]]) ?>">&laquo;</a>
        </li>
        <li>
          <a href="<?= $this->url($this->route, [],
            ['query' => ['page' => $this->previous]]) ?>">&lsaquo;</a>
        </li>
      <?php else : ?>
        <li class="disabled"><a href="#">&laquo;</a></li>
        <li class="disabled"><a href="#">&lsaquo;</a></li>
      <?php endif ?>

      <!-- Links para os números das páginas -->
      <?php foreach ($this->pagesInRange as $page) : ?>
        <?php if ($page !== $this->current) : ?>
          <li>
            <a href="<?= $this->url($this->route, [],
              ['query' => ['page' => $page]]) ?>">
              <?= $page ?>
            </a>
          </li>
        <?php else : ?>
          <li class="active">
            <a href="#"><?= $page ?></a>
          </li>
        <?php endif ?>
      <?php endforeach ?>

      <!-- Link para a próxima página -->
      <?php if (isset($this->next)) : ?>
        <li>
          <a href="<?= $this->url($this->route, [],
            ['query' => ['page' => $this->next]]) ?>">&rsaquo;</a>
        </li>
        <li>
          <a href="<?= $this->url($this->route, [],
            ['query' => ['page' => $this->last]]) ?>">&raquo;</a>
        </li>
      <?php else : ?>
        <li class="disabled"><a href="#">&rsaquo;</a></li>
        <li class="disabled"><a href="#">&raquo;</a></li>
      <?php endif ?>
    </ul>
  </div>
<?php endif ?>