<?php
$title = 'Login';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<?=$this->partial('partial/flashMessenger') ?>

<?php
$form->setAttribute('action', $this->url('login'));
$form->prepare();

$email = $form->get('email')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => $this->_('E-mail address'),
    'required'    => true,
    'autofocus'   => true
]);
$email->setLabelAttributes(['class' => 'sr-only']);

$password = $form->get('password')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => $this->_('Password'),
    'required'    => true,
]);
$password->setLabelAttributes(['class' => 'sr-only']);
?>

<div class="row">
    <br>
    <div class="col-md-3">
        <?= $this->form()->openTag($form) ?>

            <div class="form-group">
                <?= $this->formLabel($email); ?>
                <?= $this->formElement($email); ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($password); ?>
                <?= $this->formElement($password); ?>
            </div>

            <div class="form-group checkbox">
                <label>
                    <?= $this->formElement($form->get('remember_me')); ?>
                    <?= $this->_('Remember me') ?>
                </label>
            </div>

            <?= $this->formElement($form->get('redirect_url')); ?>

            <?= $this->formElement($form->get('csrf')) ?>

            <button class="btn btn-lg btn-primary btn-block" type="submit">
                <?= $this->_('Login') ?>
            </button>

        <?= $this->form()->closeTag() ?>

        <br>
        <a href="<?= $this->url('resetPassword') ?>"
        ><?= $this->_('Forgot password?') ?></a>
        <br>
        <a href="<?= $this->url('sendVerificationEmail') ?>"
            ><?= $this->_("Still haven't validated e-mail?") ?></a>
    </div>
</div>