<?php
$title = $this->_('Reset Password');
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<?=$this->partial('partial/flashMessenger') ?>

<p class="well">
<strong>ATENÇÃO!</strong> 
Ao submeter o formulário, será enviado um e-mail com um link para confirmação. 
Só então a senha será realmente alterada.
</p>

<?php
$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setLabelAttributes(['class' => 'control-label']);

$password = $form->get('password');
$password->setAttribute('class', 'form-control');
$password->setLabelAttributes(['class' => 'control-label']);

$passwordConfirm = $form->get('password_confirm');
$passwordConfirm->setAttribute('placeholder', $passwordConfirm->getLabel());
$passwordConfirm->setAttribute('class', 'form-control');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary btn-lg');

$cancel = $form->get('cancel');
$cancel->setAttribute('class', 'btn btn-default btn-lg');

$form->setAttribute('action', $this->url('resetPassword'));
$form->prepare();
?>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form) ?>

        <div class="form-group<?=$email->getMessages() ? ' has-error' : '' ?>">
            <?= $this->formLabel($email); ?>
            <?= $this->formElement($email) ?>
            <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
        </div>

        <div class="form-group<?=$password->getMessages() || $passwordConfirm->getMessages() ? ' has-error' : '' ?>">
            <?= $this->formLabel($password) ?>
            <div class="form-inline">
                <?= $this->formElement($password) ?>
                <?= $this->formElement($passwordConfirm) ?>
            </div>
            <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
            <?= $this->formElementErrors()->render($passwordConfirm, ['class' => 'help-block']) ?>
        </div>

        <?= $this->formSubmit($submit) ?>

        <?= $this->formSubmit($cancel) ?>

        <?= $this->formElement($form->get('csrf')) ?>
        
        <?= $this->form()->closeTag() ?>
    </div>
</div>