<?php
$title = $this->_('Users');
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<?= $this->partial('partial/flashMessenger') ?>

<table class="table table- table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Tipo</th>
            <th>Criação</th>
            <th>Verif. E-mail</th>
            <th>Último acesso</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td><?= $user->id ?></td>
                <td><?= $this->escapeHtml($user->name) ?></td>
                <td><?= $this->escapeHtml($user->email) ?></td>
                <td><?= $this->escapeHtml($user->type) ?></td>
                <td><?= $user->getCreatedAt('d/m/Y H:i') ?></td>
                <td><?= $user->getEmailVerifiedAt('d/m/Y H:i') ?></td>
                <td><?= $user->getAccessedAt('d/m/Y H:i') ?></td>
                <td class="text-right text-nowrap">
                    <?php if ($this->access('user.restore', 
                        ['user' => $user])): ?>
                    <a href="<?= $this->url('user', 
                        ['action' => 'restore', 'id' => $user->id]) 
                    ?>" class="btn btn-success btn-sm" 
                    onclick="return confirm('Deseja Restaurar?')"
                    >Restaurar</a>
                    <?php endif; ?>

                    <?php if ($this->access('user.destroy', 
                        ['user' => $user])): ?>
                    <a href="<?= $this->url('user', 
                        ['action' => 'delete', 'id' => $user->id]) 
                    ?>" class="btn btn-danger btn-sm" 
                    onclick="return confirm('Deseja destruir?')"
                    >Destruir</a>
                    <?php endif; ?>

                    <?php if ($this->access('user.turnIntoAdmin', 
                        ['user' => $user])): ?>
                    <a href="<?= $this->url('user', 
                        ['action' => 'turnIntoAdmin', 'id' => $user->id]) 
                    ?>" class="btn btn-primary btn-sm" 
                    onclick="return confirm('Deseja tornar admin?')"
                    >Tornar Admin</a>
                    <?php endif; ?>

                    <?php if ($this->access('user.delete', 
                        ['user' => $user])): ?>
                    <a href="<?= $this->url('user', 
                        ['action' => 'delete', 'id' => $user->id]) 
                    ?>" class="btn btn-danger btn-sm" 
                    onclick="return confirm('Deseja excluir?')"
                    >Excluir</a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<?= $this->paginationControl(
    $this->users,         // O objeto de paginação
    'sliding',            // O estilo de scrolling
    'partial/paginator',  // Caminho para a view de paginação
    ['route' => 'user']   // A rota para a url dos links
) ?>