<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('PHP Frameworks - ZF3')->setSeparator(' | ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        PHP Frameworks - ZF3
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                <?php 
                    $navigation = $this->navigation('navigation')
                        ->menu()
                        ->setMinDepth(0)  // Exibe a partir do nivel mais baixo
                        ->setMaxDepth(0); // Não exibe os submenus, se houver
                    
                    if ($this->identity()):
                        if ($this->identity()->type === 'admin'):
                            echo $navigation
                                ->setUlClass('nav navbar-nav')
                                ->renderMenu($this->navigation()->findOneById('admin'));
                        endif;

                        $this->navigation()->findOneById('user-name')->setLabel($this->identity()->name);
                        echo $navigation
                            ->setUlClass('nav navbar-nav navbar-right')
                            ->renderMenu($this->navigation()->findOneById('user'));
                    else:
                        echo $navigation
                            ->setUlClass('nav navbar-nav navbar-right')
                            ->renderMenu($this->navigation()->findOneById('guest'));
                    endif;
                ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->navigation('navigation')
                ->breadcrumbs()
                ->setMinDepth()
                ->setPartial('partial/breadcrumb') ?>
            <?= $this->content ?>
            <?php /*
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
            */ ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
